language: node_js
node_js:
  - "0.8"
  - "0.12"
  - "0.10"
  - "iojs"
  - "iojs-v1.0"
sudo: false
git:
  depth: 10
branches:
  only:
    - master
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8d6479e9fd8c597403fe
    on_success: always
    on_failure: always
script: "npm run-script test-ci"
after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"